In [1]:
import numpy as np

In [2]:
# Create numpy arrays
np.array([3, 6, 7, 10], dtype=int) # 1D array

array([ 3,  6,  7, 10])

In [3]:
a = np.array([2, 5, 10, 8, 17]) # 1D array

In [4]:
# print a
a

array([ 2,  5, 10,  8, 17])

In [5]:
# type array
type(a)

numpy.ndarray

In [6]:
b = np.array([
    [1, 2, 3, 4, 5], 
    [9, 8, 13, 14, 15]   
]) # 2D array

In [7]:
b

array([[ 1,  2,  3,  4,  5],
       [ 9,  8, 13, 14, 15]])

In [8]:
# Chaging the type
b.astype(int)

array([[ 1,  2,  3,  4,  5],
       [ 9,  8, 13, 14, 15]])

In [9]:
# Sequence
np.arange(1, 30) # 1 included, 30 last one got excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
# strides
np.arange(2, 22, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
# reshape the array
p = np.arange(2, 30).reshape(4, 7)

In [12]:
# np.ones
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# ones_like
np.ones_like((3, 4))

array([1, 1])

In [14]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
'''
    linspace
        It is also called as Linearly space , Linearly separable,in a given range at equal distance it
        creates points.
'''

np.linspace(1, 30, 10)

array([ 1.        ,  4.22222222,  7.44444444, 10.66666667, 13.88888889,
       17.11111111, 20.33333333, 23.55555556, 26.77777778, 30.        ])

In [16]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# To findout given arrays number of dimensions
n = np.array([1, 2, 3, 4])
n.ndim

1

In [18]:
# Standard deviation
np.std(n)

np.float64(1.118033988749895)

In [19]:
# fetching disired element : 4
p[1, 3]

np.int64(12)

In [20]:
p

array([[ 2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29]])

In [21]:
# Slicing
p[:, 1] # fetching 2nd column 

array([ 3, 10, 17, 24])

In [22]:
p[1:3, :3]

array([[ 9, 10, 11],
       [16, 17, 18]])

In [23]:
# Iterating 
for i in p:
    print(i)

[2 3 4 5 6 7 8]
[ 9 10 11 12 13 14 15]
[16 17 18 19 20 21 22]
[23 24 25 26 27 28 29]


In [24]:
# Comprehension list
[print(i) for i in p]

[2 3 4 5 6 7 8]
[ 9 10 11 12 13 14 15]
[16 17 18 19 20 21 22]
[23 24 25 26 27 28 29]


[None, None, None, None]

In [25]:
# Transpose array

# - 1st method
np.transpose(p)

# - 2nd method
p.T

array([[ 2,  9, 16, 23],
       [ 3, 10, 17, 24],
       [ 4, 11, 18, 25],
       [ 5, 12, 19, 26],
       [ 6, 13, 20, 27],
       [ 7, 14, 21, 28],
       [ 8, 15, 22, 29]])

In [26]:
# Ravel
p.ravel()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
# Stacking
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)

In [28]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
np.hstack((w1, w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [31]:
np.vstack((w1, w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
# Splitting
np.hsplit(w1, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [33]:
np.vsplit(w2, 1)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [34]:
# Elements-wise addition
from numpy import arange


a: arange = np.arange(100)
b: arange = np.arange(100)

In [35]:
a[::10]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
b[::3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [37]:
type(a)

numpy.ndarray

In [38]:
import time

# Create a new list for adding elements
c = []

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i]) 
end = time.time()

print("Time: ", end - start)

Time:  0.0


In [39]:
a[:4] > 3

array([False, False, False, False])

In [40]:
# Where is true, it gives the result
a[a > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [41]:
#Brosdcasting
print(a + b)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [42]:
a.size

100

In [43]:
m = b.reshape(10, 10)

In [44]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
print(a + m)

ValueError: operands could not be broadcast together with shapes (100,) (10,10) 